require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'portmanagement' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"], :hermes_enabled => true)

  target 'portmanagementTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'portmanagement-tvOS' do
  # Pods for portmanagement-tvOS

  target 'portmanagement-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
